#!/usr/bin/env python3
"""Turn the artist's car SVGs into inline <symbol>s for the highway.

    NODE_PATH=/opt/node22/lib/node_modules python3 tools/build_cars.py

Rewrites _includes/highway-svg.html (the symbols) and index.html (the car
instances), then prints the geometry css/style.css needs.

Why symbols rather than background images. The cars used to be greyscale
PNGs: colour type 4, grey + alpha, so there was no channel to put a red tail
light in, and scaling a bitmap resamples it, which is the jitter. Vector
fixes both. There are fourteen instances of only three drawings, so each
drawing becomes one <symbol> in the shared defs and each instance a two-tag
<use>; inlining the art fourteen times would add about 100KB to the page.

Per file it crops the viewBox to the drawing's own ink -- so the symbol has
no padding and keeps the aspect of the PNG it replaces, which is what lets
the existing placement percentages stand -- resolves every shape's paint from
that file's own <style> and writes it as attributes, then drops the
stylesheet, because an inline svg's <style> is not scoped to it and a bare
.st0 would repaint the other inline SVGs on this page. Tail lights are
repainted LIGHT_COLOUR with translucent halos stacked behind them, the plate
bezel is repainted BEZEL (the artist's #0c0c0c is not the page background),
and the bodywork is emitted before the lamps so the lamps sit on top of it.

Nothing here trusts the class numbering or the group names, because the three
exports disagree: left.svg names its groups and leaves its lights white,
centre.svg names nothing and pre-colours them, and the plate face is a plain
rect in two files but rotated 90 degrees in the third.
"""

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ART = ROOT / 'art' / 'cars'
SVG_INC = ROOT / '_includes' / 'highway-svg.html'
HTML = ROOT / 'index.html'
MEASURE = ROOT / 'tools' / 'measure_cars.js'

CARS = ['centre', 'left', 'right']

LIGHT_COLOUR = '#ff003d'   # the brighter of the two reds across the exports
BEZEL = '#141414'          # the page background

# Translucent copies behind each lamp, (units to inflate, opacity), painted
# largest first. Plain geometry rather than a blur filter: fourteen cars
# animate their scale continuously and a filter would re-rasterise per frame.
GLOW = [(9.0, 0.07), (5.5, 0.15), (2.5, 0.28)]

# Label inset inside the plate's white face: enough to clear a bolt hole
# (its centre inset plus its radius) with a little air after it.
BOLT_CLEARANCE = 3.5
LABEL_INSET_Y = 5.0

# Rendered width of one monospace character as a fraction of font-size, with
# the -0.02em tracking .highway__plate sets. 0.58 is the measured advance and
# leaves the longest label filling the plate exactly, which is no margin at
# all when the monospace stack resolves to a different face per platform;
# 0.623 holds it at about 93% of the plate.
EM_PER_CHAR = 0.623
LONGEST_LABEL = 'PHOTOGRAPHR'

# The two labels that would not fit are abbreviated rather than shrunk.
ABBREVIATE = {'MANUFACTURER': 'MANUFACTR', 'PHOTOGRAPHER': 'PHOTOGRAPHR'}

MARK = ('<!-- car symbols: generated by tools/build_cars.py, do not hand-edit -->',
        '<!-- end car symbols -->')

SHAPE = r'<(path|rect|circle|ellipse|line|polygon|polyline)\b([^>]*?)/?>'


def measure():
    """Ink box and plate geometry, in each drawing's own user units."""
    r = subprocess.run(['node', str(MEASURE)], capture_output=True, text=True)
    if r.returncode:
        raise SystemExit('tools/measure_cars.js failed:\n' + (r.stderr or r.stdout))
    return json.loads(r.stdout)


def parse_style(svg):
    """{class: {property: value}} from the file's own <style> block."""
    m = re.search(r'<style>(.*?)</style>', svg, re.S)
    out = {}
    if not m:
        return out
    for sel, decls in re.findall(r'([^{}]+)\{([^{}]*)\}', m.group(1)):
        d = {}
        for part in decls.split(';'):
            if ':' in part:
                k, v = part.split(':', 1)
                d[k.strip()] = v.strip()
        for cls in re.findall(r'\.([\w-]+)', sel):
            out.setdefault(cls, {}).update(d)     # source order, later wins
    return out


def light_spans(svg):
    """Character ranges of each <g id="*-lights"> block."""
    spans = []
    for m in re.finditer(r'<g[^>]*\bid="[^"]*-lights"[^>]*>', svg):
        depth, i = 0, m.start()
        for t in re.finditer(r'<g\b[^>]*?(/?)>|</g>', svg[i:]):
            if t.group(0) == '</g>':
                depth -= 1
                if depth == 0:
                    spans.append((i, i + t.end()))
                    break
            elif t.group(1) != '/':
                depth += 1
    return spans


def convert(name):
    svg = (ART / (name + '.svg')).read_text()
    styles, spans = parse_style(svg), light_spans(svg)
    body, lamps = [], []
    for m in re.finditer(SHAPE, svg):
        tag, attrs = m.group(1), dict(re.findall(r'([\w:-]+)\s*=\s*"([^"]*)"', m.group(2)))
        paint = {}
        for cls in attrs.pop('class', '').split():
            paint.update(styles.get(cls, {}))
        # A lamp is either inside a named lights group or painted one of the
        # reds; left.svg needs the first test, centre.svg needs the second.
        is_lamp = any(a <= m.start() < b for a, b in spans) or \
            bool(re.fullmatch(r'#ff00[0-9a-f]{2}', paint.get('fill', ''), re.I))
        if paint.get('fill', '').lower() == '#0c0c0c':
            paint['fill'] = BEZEL
        if is_lamp:
            paint = {'fill': LIGHT_COLOUR}
        el = '<%s %s %s/>' % (tag,
                              ' '.join('%s="%s"' % kv for kv in attrs.items()),
                              ' '.join('%s="%s"' % kv for kv in sorted(paint.items())))
        (lamps if is_lamp else body).append((re.sub(r'\s+', ' ', el).replace(' /', '/'), attrs))
    return body, lamps


def halos(lamps):
    out = []
    for _, a in lamps:
        x, y = float(a['x']), float(a['y'])
        w, h, r = float(a['width']), float(a['height']), float(a.get('rx', 0))
        for d, o in GLOW:
            out.append('<rect x="%.2f" y="%.2f" width="%.2f" height="%.2f" rx="%.2f" '
                       'fill="%s" opacity="%.2f"/>'
                       % (x - d, y - d, w + 2 * d, h + 2 * d, r + d, LIGHT_COLOUR, o))
    return out


def main():
    geo = measure()
    blocks, report = [], {}
    for name in CARS:
        body, lamps = convert(name)
        assert len(lamps) == 4, '%s: expected 4 lamps, found %d' % (name, len(lamps))
        g = halos(lamps)
        assert len(g) == 4 * len(GLOW)
        vb = geo[name]['ink']
        parts = ['  <symbol id="hw-car-%s" viewBox="%g %g %g %g">' % ((name,) + tuple(vb))]
        parts += ['    ' + e for e, _ in body] + ['    ' + e for e in g] + \
                 ['    ' + e for e, _ in lamps]
        parts.append('  </symbol>')
        blocks.append('\n'.join(parts))

        # Label box: the plate's face, inset clear of the bolt holes.
        fx, fy, fw, fh = geo[name]['face']
        inset = geo[name]['boltInset'] + geo[name]['boltRadius'] + BOLT_CLEARANCE
        lx, lw = fx + inset, fw - 2 * inset
        ly, lh = fy + LABEL_INSET_Y, fh - 2 * LABEL_INSET_Y
        report[name] = dict(
            body=len(body), lamps=len(lamps), halos=len(g), vb=vb,
            left=(lx - vb[0]) / vb[2] * 100, top=(ly - vb[1]) / vb[3] * 100,
            width=lw / vb[2] * 100, height=lh / vb[3] * 100,
            font_units=lw / (len(LONGEST_LABEL) * EM_PER_CHAR))

    # --- symbols into the highway include ---
    doc = SVG_INC.read_text()
    new = MARK[0] + '\n' + '\n'.join(blocks) + '\n  ' + MARK[1]
    if MARK[0] in doc:
        doc = re.sub(re.escape(MARK[0]) + r'.*?' + re.escape(MARK[1]), new, doc, flags=re.S)
    else:
        i = doc.index('<defs>') + len('<defs>')
        doc = doc[:i] + '\n  ' + new + '\n  ' + doc[i:]
    SVG_INC.write_text(doc)

    # --- instances: drop the scaleX squeeze, add the <use> ---
    html = HTML.read_text()
    pat = re.compile(
        r'(<div class="highway__car highway__car--(centre|left|right)"[^>]*>)'
        r'(<div class="highway__bob"[^>]*>)'
        r'<span class="highway__plate"><span[^>]*>([A-Z]+)</span></span>'
        r'(</div></div>)')
    seen = {}
    def rewrite(m):
        lane, label = m.group(2), m.group(4)
        label = ABBREVIATE.get(label, label)
        seen[lane] = seen.get(lane, 0) + 1
        return ('%s%s<svg class="highway__car-art" aria-hidden="true">'
                '<use href="#hw-car-%s"/></svg>'
                '<span class="highway__plate"><span>%s</span></span>%s'
                % (m.group(1), m.group(3), lane, label, m.group(5)))
    html, n = pat.subn(rewrite, html)
    assert n == 14, 'rewrote %d car instances, expected 14' % n
    assert 'scaleX' not in html, 'a scaleX squeeze survived'
    HTML.write_text(html)

    for name in CARS:
        r = report[name]
        print('  %-7s %2d body + %d lamps + %2d halos   viewBox %g %g %g %g'
              % (name, r['body'], r['lamps'], r['halos'], *r['vb']))
    print('  instances rewritten: %s' % seen)
    print('\n  --- geometry for .highway__car--X .highway__plate ---')
    for name in CARS:
        r = report[name]
        print('  %-7s left:%.3f%%;top:%.3f%%;width:%.3f%%;height:%.3f%%   '
              'font %.2f user units' % (name, r['left'], r['top'], r['width'],
                                        r['height'], r['font_units']))
    return 0


if __name__ == '__main__':
    sys.exit(main())
